#!/bin/sh
# build.sh
#http://tinsuke.wordpress.com/2011/11/01/how-to-compile-and-use-tesseract-3-01-on-ios-sdk-5/

GLOBAL_OUTDIR="./staticlib-ios"
LOCAL_OUTDIR="./build-ios-output"

IOS_BASE_SDK="6.1"
IOS_DEPLOY_TGT="2.2"

setenv_all()
{
	# Add internal libs
	# not real need
        # export CFLAGS="$CFLAGS -I./include -L./lib"
	
	export CXX="$DEVROOT/usr/bin/g++"
	export CC="$DEVROOT/usr/bin/gcc"

	export LD=$DEVROOT/usr/bin/ld
	export AR=$DEVROOT/usr/bin/ar
	export AS=$DEVROOT/usr/bin/as
	export NM=$DEVROOT/usr/bin/nm
	export RANLIB=$DEVROOT/usr/bin/ranlib
	export LDFLAGS="-L$SDKROOT/usr/lib/"
	
	export CPPFLAGS=$CFLAGS
	export CXXFLAGS=$CFLAGS
}

setenv_arm7()
{
	unset DEVROOT SDKROOT CFLAGS CC LD CPP CXX AR AS NM CXXCPP RANLIB LDFLAGS CPPFLAGS CXXFLAGS
	
	export DEVROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
	export SDKROOT=$DEVROOT/SDKs/iPhoneOS$IOS_BASE_SDK.sdk
	
	export CFLAGS="-arch armv7 -pipe -no-cpp-precomp -isysroot $SDKROOT -miphoneos-version-min=$IOS_DEPLOY_TGT -I$SDKROOT/usr/include/"
	
	setenv_all

	echo "-------------build arg--------------"
        echo "cc: $CC"
        echo "c++: $CXX"
        echo "CFLAGS: $CFLAGS"
        echo "LDFLAGS: $LDFLAGS"
	echo "------------------------------------"
}

setenv_arm7s()
{
	unset DEVROOT SDKROOT CFLAGS CC LD CPP CXX AR AS NM CXXCPP RANLIB LDFLAGS CPPFLAGS CXXFLAGS
	
	export DEVROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
	export SDKROOT=$DEVROOT/SDKs/iPhoneOS$IOS_BASE_SDK.sdk
	
	export CFLAGS="-arch armv7s -pipe -no-cpp-precomp -isysroot $SDKROOT -miphoneos-version-min=$IOS_DEPLOY_TGT -I$SDKROOT/usr/include/"
	
	setenv_all

	echo "-------------build arg--------------"
        echo "cc: $CC"
        echo "c++: $CXX"
        echo "CFLAGS: $CFLAGS"
        echo "LDFLAGS: $LDFLAGS"
	echo "------------------------------------"
}

setenv_i386()
{
	unset DEVROOT SDKROOT CFLAGS CC LD CPP CXX AR AS NM CXXCPP RANLIB LDFLAGS CPPFLAGS CXXFLAGS
	
	export DEVROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer
	export SDKROOT=$DEVROOT/SDKs/iPhoneSimulator$IOS_BASE_SDK.sdk
	
	export CFLAGS="-arch i386 -pipe -no-cpp-precomp -isysroot $SDKROOT -miphoneos-version-min=$IOS_DEPLOY_TGT"
	
	setenv_all
	echo "-------------build arg--------------"
        echo "cc: $CC"
        echo "c++: $CXX"
        echo "CFLAGS: $CFLAGS"
        echo "LDFLAGS: $LDFLAGS"
	echo "------------------------------------"
}

create_outdir_lipo()
{
	for lib_i386 in `find $LOCAL_OUTDIR/i386 -name "lib*.a"`; do
		lib_arm7=`echo $lib_i386 | sed "s/i386/arm7/g"`
		lib_arm7s=`echo $lib_i386 | sed "s/i386/arm7s/g"`
		lib=`echo $lib_i386 | sed "s/i386//g"`
		xcrun -sdk iphoneos lipo -arch armv7s $lib_arm7s -arch armv7 $lib_arm7 -arch i386 $lib_i386 -create -output $lib
	done
}

merge_libfiles()
{
	DIR=$1
	LIBNAME=$2
	
	cd $DIR
	for i in `find . -name "lib*.a"`; do
		$AR -x $i
	done
	$AR -r $LIBNAME *.o
	rm -rf *.o __*
	cd -
}


#######################
# build static library
#######################
rm -rf $LOCAL_OUTDIR
mkdir -p $LOCAL_OUTDIR/arm7 $LOCAL_OUTDIR/i386 $LOCAL_OUTDIR/arm7s

make clean 2> /dev/null
make distclean 2> /dev/null
setenv_arm7
./configure --host=arm-apple-darwin7 --enable-static --disable-shared
make
cp -rvf src/.libs/lib*.a $LOCAL_OUTDIR/arm7
echo "arm7 ok======================================================"

make clean 2> /dev/null
make distclean 2> /dev/null
setenv_arm7s
./configure --host=arm-apple-darwin7s --enable-static --disable-shared
make
cp -rvf src/.libs/lib*.a $LOCAL_OUTDIR/arm7s
echo "arm7s ok======================================================"

make clean 2> /dev/null
make distclean 2> /dev/null
setenv_i386
./configure --enable-static --disable-shared
make
cp -rvf src/.libs/lib*.a $LOCAL_OUTDIR/i386
echo "i386 ok======================================================"

# not use fat
#create_outdir_lipo
mkdir -p $GLOBAL_OUTDIR && cp -rvf $LOCAL_OUTDIR/* $GLOBAL_OUTDIR
echo "finished!!"
